import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev27.opdev.vn/navigos-cn/');
  await page.getByRole('textbox', { name: 'Số tiền thanh toán' }).click();
  await page.getByRole('textbox', { name: 'Số tiền thanh toán' }).fill('1,234,565');
  // await page.getByRole('textbox', { name: 'Số tiền thanh toán' }).press('Tab');
  await page.locator('div').filter({ hasText: /^Ghi chú$/ }).nth(2).click();
  await page.getByRole('textbox', { name: 'Ghi chú' }).fill('autotest');
  await page.getByRole('textbox', { name: 'Tên đơn vị mua hàng' }).click();
  await page.getByRole('textbox', { name: 'Tên đơn vị mua hàng' }).fill('nguyen van a');
  await page.getByRole('textbox', { name: 'Tên đơn vị mua hàng' }).press('Tab');
  await page.getByRole('textbox', { name: 'Số Invoice' }).fill('123456');
  await page.getByRole('textbox', { name: 'Số Invoice' }).press('Tab');
  await page.getByRole('textbox', { name: 'Số điện thoại' }).fill('0987654321');
  await page.locator('div').filter({ hasText: /^Email \*$/ }).nth(2).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('a@a.com');
  await page.locator('.checkmark').click();
  await page.getByRole('button', { name: 'Thanh toán' }).click();
  await page.locator('intercard-form span').click();
  await page.getByRole('textbox', { name: '5678 9101 1234' }).click();
  await page.getByRole('textbox', { name: '5678 9101 1234' }).dblclick();
  await page.getByRole('textbox', { name: '5678 9101 1234' }).fill('5123450000000008');
  await page.getByRole('textbox', { name: '/25' }).fill('12/27');
  await page.getByRole('textbox', { name: '123', exact: true }).fill('821');
  await page.getByRole('textbox', { name: 'NGUYEN VAN A' }).fill('3a');
  await page.getByRole('textbox', { name: 'name@email.com' }).click();
  await page.getByRole('textbox', { name: 'name@email.com' }).fill('a@aa.com');
  await page.getByRole('checkbox', { name: 'Tôi đã đọc, hiểu rõ và đồng' }).check();
  await page.getByRole('button', { name: 'Thanh toán' }).click();
  await expect(page.getByText('Thanh toán thành công!')).toBeVisible();
});

test('test3', async ({ page }) => {
  await page.goto('https://dev27.opdev.vn/th-school/');
  await page.getByText('Chọn loại thanh toánChọn loại').click();
  await page.getByText('Thanh toán học phí').click();
  await page.getByRole('textbox', { name: 'Họ tên học sinh' }).click();
  await page.getByRole('textbox', { name: 'Họ tên học sinh' }).fill('a');
  await page.getByRole('textbox', { name: 'Mã học sinh' }).click();
  await page.getByRole('textbox', { name: 'Mã học sinh' }).fill('123');
  await page.getByRole('textbox', { name: 'Lớp' }).click();
  await page.getByRole('textbox', { name: 'Lớp' }).fill('111');
  await page.getByRole('textbox', { name: 'Họ tên', exact: true }).click();
  await page.getByRole('textbox', { name: 'Họ tên', exact: true }).fill('a');
  await page.getByRole('textbox', { name: 'Số điện thoại' }).click();
  await page.getByRole('textbox', { name: 'Số điện thoại' }).fill('0985313');
  await page.getByText('Thanh toán học phí', { exact: true }).click();
});